### ISSUE TITLE
[Suggestion]Desktop Lyrics suggestion

### ISSUE THREAD

**Issue by Block81838** [Rocket1184/electron-netease-cloud-music#106]
For Desktop lyrics, **osdlyrics** is great solution. So can you add an optional dependency osdlyrics for it?

**Comment by Block81838** [comment]
Direct way is to add a feature to get lyrics from Netease, then add a button to call osdlyrics, osdlyrics will auto detect ElectronNCM

**Comment by rocka** [comment]
Not quite sure what did you mean by "add an optional dependency". I'm aware of osdlyrics, since it's a gtk project, there is not a direct way to "depend on" it, while we are in JavaScript land. If you mean add an optional dependency in ElectronNCM's [AUR package](https://aur.archlinux.org/packages/electron-netease-cloud-music/), it should be fine.

As for "add a button to call osdlyrics", I personaly think it's not the optimal solution. osdlyrics can start other media players when it starts, and exit when their MPRIS service goes offline. And there's also [Netease lyric source](https://github.com/osdlyrics/osdlyrics/blob/master/lyricsources/netease/netease.py) available, which works well with ElectronNCM. For now it might be good enough, and ElectronNCM may have it's own lyric window implemention in future versions.
