### ISSUE TITLE
[Bug] Login issue

### ISSUE THREAD

**Issue by Block81838** [Rocket1184/electron-netease-cloud-music#111]
I cant login via phone num, and also tried webpage login, not work

I tried to delete the config file and relogin, still encountered this issue.

**OS**: Archlinux
**Version**: 0.9.25

![Screenshot_20201119004444](https://user-images.githubusercontent.com/22847876/99643680-d4e45600-2a01-11eb-9cad-c2ab39345be2.png)

**Comment by rocka** [comment]
Can you login on the website ( https://music.163.com/ ) from browser? And what's the error message when you try webpage login?

**Comment by Block81838** [comment]
I can login on  web page

**Comment by rocka** [comment]
Please try the latest CI build from https://ncm-releases.herokuapp.com/

download asar, and run with

```console
$ electron /path/to/electron-netease-cloud-music_*.asar
```

---

Since your phone number is not in China (+86), you may need to prepend your country code to it when login in App with phone number, eg:

```
86 12312341234
```

Or just try webpage login. Both login methods should all be fixed.

**Comment by Block81838** [comment]
Hi there,
I tried that asar pack, it works via webpage login method.
But the phone num login still not work for me.
I used phone num with area code `1xxxxxxxxxx`
It showed an error, when I tried to login with number without area code, it did no effect after clicking login, no error, nothing happed, just chilled there
As u know, you can choose an area code when u login to the site
![Screenshot_20201120214400](https://user-images.githubusercontent.com/22847876/99868742-fff1b580-2b79-11eb-9b84-2a8998f1618b.png)

**Comment by rocka** [comment]
Glad to know that webpage login works.

And I forgot to mention that if you use phone number with country code, you have to put a space between country code and phone number, eg: 

```
1 2332332233
```

because it can't determine hove long the country code is, and I'm too lazy to put a dropdown widget ...

Since it works, I'll close the issue.

**Comment by Block81838** [comment]
okay, thanks
